on:
  push:
    branches:
      - main

jobs:
  jo-linux:
    name: Compile in linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install Pyinstaller
        run: pip install -r requirements.txt 
      - name: Compile
        run: |
          cd bin
          cd linux
          pyinstaller --onefile ../../TFserver.py
          pyinstaller --onefile --noconsole ../../client_gui.py
          pyinstaller --onefile --noconsole ../../client_lite.py
          rm TFserver.spec
          rm client_gui.spec
          rm client_lite.spec
          rm -rf build/*
          rmdir build
          cp -rf dist/TFserver .
          cp -rf dist/client_gui .
          cp -rf dist/client_lite .
          rm dist/*
          rmdir dist
          cd ../..
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add .
          git commit -m "[Bot]Push binary file"
          git push
  jo-windows:
    name: Compile in windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install Pyinstaller
        run: pip install -r requirements.txt 
      - name: Compile
        run: |
          cd bin
          cd windows
          pyinstaller --onefile ../../TFserver.py
          pyinstaller --onefile --noconsole ../../client_gui.py
          pyinstaller --onefile --noconsole ../../client_lite.py
          rm TFserver.spec
          rm client_gui.spec
          rm client_lite.spec
          Copy-Item -Path ./dist/* -destination ./
          remove-item -path "./dist" -recurse
          remove-item -path "./build" -recurse
          cd ../..
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add .
          git commit -m "[Bot]Push binary file"
          git push
        
